services:
  - type: web
    name: travello
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn travelloMain.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: travello.onrender.com
      - key: DATABASE_URL
        fromDatabase:
        name: travello_db
        property: connectionString

      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password

databases:
  - name: travello_db              # Internal Render name (lowercase + underscore)
    databaseName: travello         # Actual PostgreSQL DB name (lowercase)
    user: travello_user            # PostgreSQL username (lowercase)
