# Generated by Django 4.2.21 on 2025-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=None)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(max_length=50)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
